### ISSUE TITLE
Furigana sometimes not being properly split

### ISSUE THREAD

**Issue by clnhs** [WeDontPanic/Jotoba#26]
I was building some project based your API and noticed errors in the furigana for some words such as "日本語", but only in the "words" path of the API (works fine in "sentences" AFAIK).

**Describe the bug**
Querying the API for "日本語", as an example, returns broken furigana. The "sentences" path of the API doesn't have this issue as far as I'm aware.

**To Reproduce**
1. Query API on path `https://jotoba.de/api/search/words` with body `{"query":"日本語","language":"English","no_english":false}`
2. Look at results. For example, words > Index 0 > reading > furigana is `[日本語|にほんご]` instead of the expected `[日本語|に|ほん|ご]`.

**Expected behavior**
Expected furigana separation `[日本語|に|ほん|ご]`, got `[日本語|にほんご]`.

**Comment by JojiiOfficial** [comment]
This is not really an issue. There are cases where furigana can't be properly generated since the kanji readings don't allow the given composition (日 does not have a に reading according to kanjidict). In order to provide 100% correct furigana-splittings, such cases are solved by using the whole reading as furigana for a word. In this case I could correctly split the furigana, since に is the only possible reading for the first kanji but there are cases where its impossible to tell... So guessing the right one doesn't really solve the issue.
If you can provide a resource with correct furigana readings(splittings) I can look into it.

**Comment by clnhs** [comment]
> kanji readings don't allow the given composition (日 does not have a に reading according to kanjidict)

Yeah, I realized this the other day. Somehow never crossed my mind.

> So guessing the right one doesn't really solve the issue. If you can provide a resource with correct furigana readings(splittings) I can look into it.

I suppose it's a much easier said than done (and am not familiar enough with Rust), but wouldn't cross-checking with your sentences db basically solve this issue? I suppose it's not dynamically generated, so it would be a one-time process which can probably be automated based on the amount of splits (e.g. 日本語 has three splits in the sentences db, but one in the words db). 

Though admittedly there are issues with the sentences split as well, such as 取引所 having a split issue but the right kana, whereas sentences have no split issue (`[取引|とり|ひき][所|しょ]`) but use しょ instead of じょ. And one would need to know whether or not to thrust Tatoeba's splits.

So my understanding is solving these discrepancies would necessitate:
1. Comparing word furigana split with sentence furigana split
2. Checking which kana differs and replacing them with the ones coming from the JMdict... which I'm inclined is more reliable than Tatoeba. This would both fix the issues in the sentences db and words db.

Am I missing anything?

There's a lot on your plate already so I can see why this may not be a priority (esp. since there's also a need to ensure accuracy), but I feel it should be mentionned in the API docs that furigana may not match. I originally thought they were included in JMdict because Jisho.org does well with furigana, but it's obviously not the case.

**Comment by JojiiOfficial** [comment]
I don't like the idea to cross check furigana with the sentences. Those are user generated, and as you already stated, they (can) contain errors. In that case Tatoeba can be blamed but I don't want to generate/display wrong furigana which I'm responsible for. Since this is a dictionary and user (at least me) approach it with the mindset that the content is somewhat correct, I prefer to keep is as correct as possible.


> and am not familiar enough with Rust

Those are generated at preprocessing time. If you have a better working tool (or write one) the language does not matter as long as it can be merged with the jmdict data. In case you're interested [this](https://github.com/WeDontPanic/Jotoba/blob/dev/lib/japanese/src/furigana/generate.rs) is the algo I came up with

**Comment by clnhs** [comment]
Thanks for the pointers. I'll see what I can do.

**Comment by JojiiOfficial** [comment]
From v2 on we're going to use this furigana dataset to display and split furigana. Please contact or contribute to this repository for improvements or changes as furigana itself won't be a task of Jotoba.
https://github.com/Doublevil/JmdictFurigana
